services:
  web:
    build: .
    container_name: spring-web
    ports:
      - "8443:8080"
      - "2222:22"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/B-Sam_Nangalex-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hello@123

  mysql:
    image: mysql:8.4
    container_name: spring-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: B-Sam_Nangalex-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: spring-phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Hello@123

volumes:
  mysql_data:
